version: '2'

services:
  customer_web:
    build: ./Customer
    command: bash -c "python3 ./Customer/manage.py makemigrations && python3 ./Customer/manage.py migrate && python3 ./Customer/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always

  order_web:
    build: ./OrderApi
    command: bash -c "python3 ./OrderApi/manage.py makemigrations && python3 ./OrderApi/manage.py migrate && python3 ./OrderApi/manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/code
    ports:
      - 8002:8002
    restart: always
    


  nginx:
    build: ./Web
    ports:
      - 80:80
    links:
      - customer_web
      - order_web
    depends_on:
        - customer_web
        - order_web