# Generated by Django 3.2.5 on 2021-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAPI', '0002_order_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.UUIDField(unique=True),
        ),
    ]
