# Generated by Django 3.2.5 on 2021-08-02 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adressLine', models.TextField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('city_code', models.IntegerField()),
            ],
            options={
                'db_table': 'store_Adress',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('adress', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerAPI.adress')),
            ],
            options={
                'db_table': 'store_Customers',
            },
        ),
    ]
